let gamesByGenera = {
  Action : [
    {"Spider-Man" : 58134},
    {"Grand Theft Auto V" : 3498}, 
    {"Final Fantasy VII" : 259801},
    {"Overwatch" : 22508},
    {"Nioh" : 401},
    {"Sekiro: Shadows Die Twice" : 2489},
    {"Dead Cells" : 11726},
    {"Control"  : 58812},
    {"God Of War" : 29179},
    {"Days Gone" : 29338},
  ],
  Adventure : [
    {"Uncharted 4": 4475}, 
    {"The Witcher III - The Wild Hunt" : 3328}, 
    {"Horizon Zero  Dawn" : 254542},
    {"Borderlands 3" : 58617},
    {"The Legend of Zelda: Breath of the Wild" : 22511},
    {"Fortnite": 28131}, 
    {"Marvel Ultimate Alliance" : 37357},
    {"The Elder Scrolls V: Skyrim" : 5679},
    {"Dragon Quest XI" : 58084},
    {"Rise of the Tomb Rider" : 7689},
  ],
  Family : [
    {"Minecraft" : 22509},
    {"Super Mario Odyssey" : 59632},
    {"Rocket League" : 3272},
    {"Super Smash Bros. Ultimate" : 23763}, 
    {"Yoshi's Crafted World" : 27989},
    {"Stardew Valley" : 257201},
    {"Mario Tennis Aces" : 51609},
    {"Mario Kart 8 Deluxe"  : 23165},
    {"Splatoon 2" : 28024},
    {"Animal Crossing New Horizons" : 421698},
    {"Little Big Planet 3"  : 3501},
    {"Lego Dimensions" : 27988},
  ],
  Horror : [
    {"Doom" : 2454},
    {"Doom Eternal" : 58777},
    {"Resident Evil 7" : 480},
    {"Mortal Kombat 11" : 274480},
    {"Amnesia: The Dark Descent" : 13668},
    {"The Evil Within" : 3554},
    {"Prey" : 39},
    {"Soma" : 3168},
    {"Until Dawn" : 3209},
    {"Alien Isolation" : 3556},
  ],
  Mystery : [
    {"Death Stranding" : 50738},
    {"Star Wars Jedi: Fallen Order": 257201},
    {"Luigi's Mansion 3" : 236697}, 
    {"Bayonetta 2" : 23760}, 
    {"Hollow Knight" : 9767},
    {"Bloodstained: Ritual of the Night" : 61176},
    {"L.A. Noire" : 4514},
    {"Sherlock Holmes: The Devil's Daugther" : 965},
    {"The Shapeshifting Detective" : 244806},
    {"The Sinking City" : 58811},
    {"Firewatch" : 2819},
  ],
  Romance : [
    {"Persona 5" : 49},
    {"Dragon's Dogma" : 4297},
    {"Alone with You" : 1438},
    {"Arcade Spirits" : 60632},
    {"Divinity Orginal Sin II" : "xxxxxxx"},
    {"Steins;Gate" : "xxxxxxx"},
    {"Mass Effect: Andromeda" : "xxxxxxx"},
    {"Pillars of Eternity" : "xxxxxxx"},
    {"GreedFall" : "xxxxxxx"},
    {"Song of Unleash" : "xxxxxxx"},

  ],
  Thriller : [
    {"The Last of US" : "xxxxxxx"},
    {"Bloodborne" : "xxxxxxx"},
    {"Dark Souls III" : "xxxxxxx"},
    {"Hellblade: Senua's Sacrifice" : "xxxxxxx"},
    {"Astral Chain" : "xxxxxxx"}, 
    {"Diablo III" : "xxxxxxx"},
    {"Wolfenstein The New Colosss" : "xxxxxxx"},
    {"Nier:Automata" : "xxxxxxx"},
    {"Mass Effect Andromeda" : "xxxxxxx"},
    {"Assassin's Creed Oddysey" : "xxxxxxx"},
    {"Fire Emblem The Three Houses" : "xxxxxxx"},

  ],
  Western : [
    {"Red Dead Redemption II" : "xxxxxxx"},
    {"Red Dead Revolver"  : "xxxxxxx"},
    {"SteamWorld Dig"  : "xxxxxxx"},
    {"Secret Ponchos"  : "xxxxxxx"},
    {"El Hijo" : "xxxxxxx"},
    {"Wild Guns Reloaded" : "xxxxxxx"},
    {"West of Dead" : "xxxxxxx"},
    {"Little Town Hero"  : "xxxxxxx"},
    {"Red Dead Redemption"  : "xxxxxxx"},
  ],
}

let weathers = ["Mist","Smoke","Haze","Dust","Fog","Sand","Ash",
"Squall","Tornado","Snow","Rain","Drizzle","Thunderstorm",
"Clear","Clouds"]


let vgGeneres = ["Action", "Indie", "Adventure", "RPG", "Strategy", 
                  "Shooter", "Casual", "Simulation", "Puzzle", "Arcade", 
                  "Platformer", "Racing", "Sports", "Massively Multiplayer", 
                  "Family", "Fighting", "Board Games", "Educational", "Card"]


export default gamesByGenera