let gamesByGenera = {
  Action : [
    {"Spider-Man" : 58134},
    {"Grand Theft Auto V" : 3498}, 
    {"Final Fantasy VII" : 259801},
    {"Overwatch" : 22508},
    {"Nioh" : 401},
    {"Sekiro: Shadows Die Twice" : 2489},
    {"Dead Cells" : 11726},
    {"Control"  : 58812},
    {"God Of War" : 29179},
    {"Days Gone" : 29338},
  ],
  Adventure : [
    {"Uncharted 4": "xxxxxxx"}, 
    {"The Witcher III - The Wild Hunt" : "xxxxxxx"}, 
    {"Horizon Zero  Dawn" : "xxxxxxx"},
    {"Borderlands 3" : "xxxxxxx"},
    {"The Legend of Zelda: Breath of the Wild" : "xxxxxxx"},
    {"Fortnite": "xxxxxxx"}, 
    {"Marvel Ultimate Alliance" : "xxxxxxx"},
    {"The Elder Scrolls V: Skyrim" : "xxxxxxx"},
    {"Dragon Quest XI" : "xxxxxxx"},
    {"Rise of the Tomb Rider" : "xxxxxxx"},
  ],
  Family : [
    {"Minecraft" : "xxxxxxx"},
    {"Super Mario Odyssey" : "xxxxxxx"},
    {"Rocket League" : "xxxxxxx"},
    {"Super Smash Bros. Ultimate" : "xxxxxxx"}, 
    {"Yoshi's Crafted World" : "xxxxxxx"},
    {"Stardew Valley" : "xxxxxxx"},
    {"Mario Tennis Aces" : "xxxxxxx"},
    {"Mario Kart 8 Deluxe"  : "xxxxxxx"},
    {"Splatoon 2" : "xxxxxxx"},
    {"Animal Crossing New Horizons" : "xxxxxxx"},
    {"Little Big Planet 3"  : "xxxxxxx"},
    {"Lego Dimensions" : "xxxxxxx"},
  ],
  Horror : [
    {"Doom" : "xxxxxxx"},
    {"Doom Eternal" : "xxxxxxx"},
    {"Resident Evil 7" : "xxxxxxx"},
    {"Mortal Kombat 11" : "xxxxxxx"},
    {"Amnesia: The Dark Descent" : "xxxxxxx"},
    {"The Evil Within" : "xxxxxxx"},
    {"Prey" : "xxxxxxx"},
    {"Soma" : "xxxxxxx"},
    {"Until Dawn" : "xxxxxxx"},
    {"Alien Isolation" : "xxxxxxx"},
  ],
  Mystery : [
    {"Death Stranding" : "xxxxxxx"},
    {"Star Wars Jedi: Fallen Order": "xxxxxxx"},
    {"Luigi's Mansion 3" : "xxxxxxx"}, 
    {"Bayonetta 2" : "xxxxxxx"}, 
    {"Hollow Knight" : "xxxxxxx"},
    {"Bloodstained: Ritual of the Night" : "xxxxxxx"},
    {"L.A. Noire" : "xxxxxxx"},
    {"Sherlock Holmes: The Devil's Daugther" : "xxxxxxx"},
    {"The Shapeshifting Detective" : "xxxxxxx"},
    {"The Sinking City" : "xxxxxxx"},
    {"Firewatch" : "xxxxxxx"},
  ],
  Romance : [
    {"Persona 5" : "xxxxxxx"},
    {"Dragon's Dogma" : "xxxxxxx"},
    {"Alone with You" : "xxxxxxx"},
    {"Arcade Spirits" : "xxxxxxx"},
    {"Divinity Orginal Sin II" : "xxxxxxx"},
    {"Steins;Gate" : "xxxxxxx"},
    {"Mass Effect: Andromeda" : "xxxxxxx"},
    {"Pillars of Eternity" : "xxxxxxx"},
    {"GreedFall" : "xxxxxxx"},
    {"Song of Unleash" : "xxxxxxx"},

  ],
  Thriller : [
    {"The Last of US" : "xxxxxxx"},
    {"Bloodborne" : "xxxxxxx"},
    {"Dark Souls III" : "xxxxxxx"},
    {"Hellblade: Senua's Sacrifice" : "xxxxxxx"},
    {"Astral Chain" : "xxxxxxx"}, 
    {"Diablo III" : "xxxxxxx"},
    {"Wolfenstein The New Colosss" : "xxxxxxx"},
    {"Nier:Automata" : "xxxxxxx"},
    {"Mass Effect Andromeda" : "xxxxxxx"},
    {"Assassin's Creed Oddysey" : "xxxxxxx"},
    {"Fire Emblem The Three Houses" : "xxxxxxx"},

  ],
  Western : [
    {"Red Dead Redemption II" : "xxxxxxx"},
    {"Red Dead Revolver"  : "xxxxxxx"},
    {"SteamWorld Dig"  : "xxxxxxx"},
    {"Secret Ponchos"  : "xxxxxxx"},
    {"El Hijo" : "xxxxxxx"},
    {"Wild Guns Reloaded" : "xxxxxxx"},
    {"West of Dead" : "xxxxxxx"},
    {"Little Town Hero"  : "xxxxxxx"},
    {"Red Dead Redemption"  : "xxxxxxx"},
  ],
}

let weathers = ["Mist","Smoke","Haze","Dust","Fog","Sand","Ash",
"Squall","Tornado","Snow","Rain","Drizzle","Thunderstorm",
"Clear","Clouds"]


let vgGeneres = ["Action", "Indie", "Adventure", "RPG", "Strategy", 
                  "Shooter", "Casual", "Simulation", "Puzzle", "Arcade", 
                  "Platformer", "Racing", "Sports", "Massively Multiplayer", 
                  "Family", "Fighting", "Board Games", "Educational", "Card"]


export default gamesByGenera